### ISSUE TITLE
结果无法复现

### ISSUE THREAD

**Issue by zdgithub** [taishan1994/UIE_CLUENER#1]
大佬，你好！按照readme里的参数训练模型，并不能复现你的结果。请问是哪些超参还要调整吗？
我训练后的model_best的checkpoint-11840，远大于你的checkpoint-1800，你是仅仅设置了3个epoch吗？

**Comment by taishan1994** [comment]
> 大佬，你好！按照readme里的参数训练模型，并不能复现你的结果。请问是哪些超参还要调整吗？ 我训练后的model_best的checkpoint-11840，远大于你的checkpoint-1800，你是仅仅设置了3个epoch吗？

不是额，你最高f1有多少。

**Comment by zdgithub** [comment]
@taishan1994 在dev上的最高f1只有81.75，我看你的readme里的evaluate  f1加起来好像有85

**Comment by zdgithub** [comment]
明白了，我加载的不是最优的模型，感谢大佬！

**Comment by zdgithub** [comment]
大佬，我dev上的f1最高为81.7，但是提交到cluener榜单后，只有80.46，没法复现你的81.66的结果，超参和你的readme里设置的一样

**Comment by taishan1994** [comment]
> 大佬，我dev上的f1最高为81.7，但是提交到cluener榜单后，只有80.46，没法复现你的81.66的结果，超参和你的readme里设置的一样

我的那个结果也是UIE自己计算出来的，不是上传磅单的结果。

**Comment by zdgithub** [comment]
@taishan1994 哦哦，大佬，你上传过榜单看看test效果吗？我把你仓库里的clean_result_base.txt的结果格式处理后，上传到榜单，也只有80多的，感觉uie自己计算的可能和榜单计算的有较大区别？

**Comment by taishan1994** [comment]
> @taishan1994 哦哦，大佬，你上传过榜单看看test效果吗？我把你仓库里的clean_result_base.txt的结果格式处理后，上传到榜单，也只有80多的，感觉uie自己计算的可能和榜单计算的有较大区别？

没有试过，可能你换个更大的模型效果会好些。

**Comment by zdgithub** [comment]
哦哦，好的，多谢大佬解答
